#pragma once
#include <cstdint>
#include <string>
#include <vector>

namespace Core {

    class OffsetsClass {
    public:

        uintptr_t m_World,
            m_ReplayInterFace,
            m_ViewPort,
            m_BlipList,
            m_CamGameplayDirector,
            m_HandleBullet,
            m_LocalPlayer,
            m_Camera,
            m_SwapChain,
            m_PointerToHandle,
            m_BulletHandler,
            m_CurrentPedWeapon,
            m_IsCutscene,
            m_GetRenderingCam,
            m_FreecamNop,
            m_IsPedFalling,
            m_GetPedAmmoByType,
            m_GetAmmoInPedWeapon,
            m_GetSelectedPedWeapon,
            m_GetBestPedWeapon,
            m_GetCurrentPedWeapon,
            m_SHOOT_SINGLE_BULLET_BETWEEN_COORDS,
            m_RequestAnimDict,
            m_HasAnimDictLoaded,
            m_TaskPlayAnim,
            m_RageAtHashCompute,
            m_FindAnimDictSlot,
            m_StreamingRequestBuild,
            m_SetEntityHealthNative,
            m_CPedIntelligenceClearTasks,
            m_CPedIntelligenceFlushImmediately,
            m_CPedSetIsCrouching,
            m_CPhysicalDetachFromParent,
            m_CommandIsEntityAttached,
            m_CommandNetworkRequestControlOfEntity,
            m_CommandDetachEntity,
            m_SetPedInVehicle,
            m_SetVehicleNumberPlateText,
            m_SetEntityRotation,
            m_SoloSessionStart,
            m_SoloSessionEnd,
            m_GetSerialisePackedAddress,
            m_PatchButt,
            m_SilentPatchModule,
            m_GetPedBoneCoords,
            m_EntityPool,
            m_SetForwardSpeed,
            m_IsNetworkTutorialSession,
            m_IsNetworkTutorialSession2,
            m_GetPedLastWeaponImpactCoord,
            m_HasEntityBeenDamagedByWeapon,
            m_ClonedSeatShuffleSerialise,
            m_NetSyncPattern,
            m_SetEntityCoordsBlock,
            m_AttachEntityToEntityBlock;

        uintptr_t m_SilentAim,
            m_InfiniteAmmo0,
            m_InfiniteAmmo1,
            m_MagicBulletsPatch,
            m_ArmsKinematics,
            m_LegsKinematics,
            m_InfiniteCombatRoll,
            m_GiveWeapon,
            m_TriggerbotFunc,
            m_BoneMaskFunc,
            m_GetGameplayCamRot,
            m_GetFinalRenderedCamRot,
            m_GetGameplayCamCoord,
            m_GetPedBoneIndex,
            m_CreateObject,
            m_AttachEntityToEntity,
            m_HasEntityClearLosToEntity,
            m_ClearPedTasks,
            m_SetCurrentPedWeapon,
            m_ExplodeVehicle,
            m_AddWeapon,
            m_CreateVehicle,
            m_SetPedIntoVehicle,
            m_GetHandleByPointer,
            m_ExplodeVehicleRemote;

        uintptr_t m_LastVehicle,
            m_Handling,
            m_VehicleEngineHealth,
            m_PlayerInfo,
            m_FragInst,
            m_Armor,
            m_Recoil,
            m_BoneList,
            m_PedFlag,
            m_Spread,
            m_NoReload,
            m_BulletDamage,
            m_Range,
            m_WeaponManager,
            m_WeaponObject,
            m_WeaponInfo,
            m_VehicleManager,
            m_VehicleDoorsLockState,
            m_VehiclePrimaryColor,
            m_VehicleSecondaryColor,
            m_EntityType,
            m_Speed,
            m_SwimSpeed,
            m_WaterSpeed,
            m_MaxHealth,
            m_VehicleDriver,
            m_CObject,
            m_NoRagDoll,
            m_CWeapon,
            m_PlayerId,
            m_CitizenNamesModBase,
            m_NetIdToNamesEntry,
            m_SeatBealt,
            m_AimCPedPatternResult,
            m_FrameFlag,
            m_VehicleState,
            m_FreecanPatch,
            m_CamFollowOffset,
            m_CamViewOffset,
            m_CamPosOffset,
            m_CamDataOffset,
            m_CamFovOffset,
            m_CamDistanceOffset,
            m_GameplayCamHolder,
            m_GameplayCamTarget,
            m_Velocity,
            m_VehicleExtras,
            m_RocketSpeed,
            m_OffsetPool,
            m_CameraX,
            m_CamerazX,
            m_CameraY,
            m_CameraZ,
            m_WeaponDamageModifier,
            m_WeaponDefenseModifier,
            m_WeaponDefenseModifier2,
            m_VehicleDamageModifier,
            m_VehicleDefenseModifier,
            m_MeleeWeaponDamageModifier,
            m_MeleeWeaponDefenseModifier,
            m_PlayerStamina,
            m_Room,
            m_BulletInstance,
            m_PlayerNamesBase,
            m_PlayerAimingAt,
            m_SkySettings,
            m_bRenderPhaseSeeThrough,
            m_ColorFar, m_ColorNear,
            m_PlayerColorOutline, m_PlayerColorInside,
            m_PostFXPass,
            m_StarFieldIntensity;

        uintptr_t m_Timecycle;
        uintptr_t m_TimecycleTs;
        uintptr_t m_TimecycleBufferIdx;
        uintptr_t m_TimecycleOverride;

        int CurrentBuild;
        std::string ServerIp;

    };

    inline OffsetsClass g_Offsets;
}
