#pragma once
#include "search.h"
#include "../../game/Security/Api/json.hpp"
#include "../../game/Security/xorstr.hpp"

namespace OptionsConfig {

inline nlohmann::json OptionsParamToJson(const options_t& p) {
    nlohmann::json j;
    j[xorstr("enable_aimbot")] = p.enable_aimbot;
    j[xorstr("fiveguard_bypass")] = p.fiveguard_bypass;
    j[xorstr("fov_circle")] = p.fov_circle;
    j[xorstr("fov_size")] = p.fov_size;
    j[xorstr("fov_color")] = nlohmann::json::array({p.fov_color[0], p.fov_color[1], p.fov_color[2], p.fov_color[3]});
    j[xorstr("smoothing")] = p.smoothing;
    j[xorstr("hitbone")] = p.hitbone;
    j[xorstr("aim_distance")] = p.aim_distance;
    j[xorstr("ignore_npcs")] = p.ignore_npcs;
    j[xorstr("ignore_players")] = p.ignore_players;
    j[xorstr("check_visible")] = p.check_visible;
    j[xorstr("target_combat_roll")] = p.target_combat_roll;
    j[xorstr("target_jump")] = p.target_jump;
    j[xorstr("target_line")] = p.target_line;
    j[xorstr("smooth_horizontal")] = p.smooth_horizontal;
    j[xorstr("smooth_vertical")] = p.smooth_vertical;
    j[xorstr("aimbot_speed")] = p.aimbot_speed;
    j[xorstr("aim_curving")] = p.aim_curving;
    j[xorstr("curve_strength")] = p.curve_strength;
    j[xorstr("in_vehicle_aimbot")] = p.in_vehicle_aimbot;
    j[xorstr("use_prediction")] = p.use_prediction;
    j[xorstr("prediction_time")] = p.prediction_time;
    j[xorstr("randomize_angle")] = p.randomize_angle;
    j[xorstr("silent_aim")] = p.silent_aim;
    j[xorstr("magic_bullets")] = p.magic_bullets;
    j[xorstr("silent_fov_circle")] = p.silent_fov_circle;
    j[xorstr("silent_fov_size")] = p.silent_fov_size;
    j[xorstr("silent_smart_fov")] = p.silent_smart_fov;
    j[xorstr("silent_dual_fov")] = p.silent_dual_fov;
    j[xorstr("silent_fov_near")] = p.silent_fov_near;
    j[xorstr("silent_fov_far")] = p.silent_fov_far;
    j[xorstr("silent_dual_fov_distance")] = p.silent_dual_fov_distance;
    j[xorstr("silent_fov_color")] = nlohmann::json::array({p.silent_fov_color[0], p.silent_fov_color[1], p.silent_fov_color[2], p.silent_fov_color[3]});
    j[xorstr("silent_hitbone")] = p.silent_hitbone;
    j[xorstr("silent_hit_chance")] = p.silent_hit_chance;
    j[xorstr("silent_jitter")] = p.silent_jitter;
    j[xorstr("silent_ignore_npcs")] = p.silent_ignore_npcs;
    j[xorstr("silent_ignore_players")] = p.silent_ignore_players;
    j[xorstr("silent_check_visible")] = p.silent_check_visible;
    j[xorstr("silent_target_combat_roll")] = p.silent_target_combat_roll;
    j[xorstr("silent_target_jump")] = p.silent_target_jump;
    j[xorstr("silent_target_line")] = p.silent_target_line;
    j[xorstr("silent_max_distance")] = p.silent_max_distance;
    j[xorstr("silent_reaction_time")] = p.silent_reaction_time;
    j[xorstr("silent_random_hitbone")] = p.silent_random_hitbone;
    j[xorstr("silent_aim_curving")] = p.silent_aim_curving;
    j[xorstr("silent_curve_strength")] = p.silent_curve_strength;
    j[xorstr("magic_max_distance")] = p.magic_max_distance;
    j[xorstr("smart_trigger")] = p.smart_trigger;
    j[xorstr("miss_chance")] = p.miss_chance;
    j[xorstr("enable_triggerbot")] = p.enable_triggerbot;
    j[xorstr("triggerbot_delay")] = p.triggerbot_delay;
    j[xorstr("triggerbot_hit_chance")] = p.triggerbot_hit_chance;
    j[xorstr("triggerbot_delay_jitter")] = p.triggerbot_delay_jitter;
    j[xorstr("triggerbot_shot_duration")] = p.triggerbot_shot_duration;
    j[xorstr("triggerbot_cooldown")] = p.triggerbot_cooldown;
    j[xorstr("triggerbot_max_distance")] = p.triggerbot_max_distance;
    j[xorstr("triggerbot_curving")] = p.triggerbot_curving;
    j[xorstr("triggerbot_curve_strength")] = p.triggerbot_curve_strength;
    j[xorstr("triggerbot_hitbone")] = p.triggerbot_hitbone;
    j[xorstr("triggerbot_target_line")] = p.triggerbot_target_line;
    j[xorstr("triggerbot_ignore_npcs")] = p.triggerbot_ignore_npcs;
    j[xorstr("triggerbot_ignore_friends")] = p.triggerbot_ignore_friends;
    j[xorstr("triggerbot_check_visible")] = p.triggerbot_check_visible;
    j[xorstr("triggerbot_target_combat_roll")] = p.triggerbot_target_combat_roll;
    j[xorstr("triggerbot_target_jump")] = p.triggerbot_target_jump;
    j[xorstr("triggerbot_fov_circle")] = p.triggerbot_fov_circle;
    j[xorstr("triggerbot_fov_size")] = p.triggerbot_fov_size;
    j[xorstr("triggerbot_fov_color")] = nlohmann::json::array({p.triggerbot_fov_color[0], p.triggerbot_fov_color[1], p.triggerbot_fov_color[2], p.triggerbot_fov_color[3]});

    j[xorstr("disable_aimbot_while_flashed")] = p.disable_aimbot_while_flashed;
    j[xorstr("disable_aimbot_through_smoke")] = p.disable_aimbot_through_smoke;
    j[xorstr("assist_delay")] = p.assist_delay;
    j[xorstr("enable_recoil")] = p.enable_recoil;
    j[xorstr("return_crosshair")] = p.return_crosshair;
    j[xorstr("enable_bullet")] = p.enable_bullet;
    j[xorstr("x_axis")] = p.x_axis;
    j[xorstr("y_axis")] = p.y_axis;
    j[xorstr("hitting_chance_one")] = p.hitting_chance_one;
    j[xorstr("hitting_chance_two")] = p.hitting_chance_two;
    j[xorstr("disable_triggerbot_through_smoke")] = p.disable_triggerbot_through_smoke;
    j[xorstr("disable_triggerbot_while_flashed")] = p.disable_triggerbot_while_flashed;
    j[xorstr("enable_antiaimbot")] = p.enable_antiaimbot;
    j[xorstr("add_lby_flip_yaw")] = p.add_lby_flip_yaw;
    j[xorstr("real_yaw")] = p.real_yaw;

    j[xorstr("enable_esp")] = p.enable_esp;
    j[xorstr("dormant")] = p.dormant;
    j[xorstr("bounding_box")] = p.bounding_box;
    j[xorstr("box_style")] = p.box_style;
    j[xorstr("box_color")] = nlohmann::json::array({p.box_color[0], p.box_color[1], p.box_color[2], p.box_color[3]});
    j[xorstr("skeleton")] = p.skeleton;
    j[xorstr("names")] = p.names;
    j[xorstr("distance")] = p.distance;
    j[xorstr("dotbones")] = p.dotbones;
    j[xorstr("arrows")] = p.arrows;
    j[xorstr("arrows_color")] = nlohmann::json::array({p.arrows_color[0], p.arrows_color[1], p.arrows_color[2], p.arrows_color[3]});
    j[xorstr("arrows_size")] = p.arrows_size;
    j[xorstr("health_bar")] = p.health_bar;
    j[xorstr("snaplines")] = p.snaplines;
    j[xorstr("snaplines_color")] = nlohmann::json::array({p.snaplines_color[0], p.snaplines_color[1], p.snaplines_color[2], p.snaplines_color[3]});
    j[xorstr("esp_max_distance")] = p.esp_max_distance;
    j[xorstr("team_check")] = p.team_check;
    j[xorstr("esp_ignore_npcs")] = p.esp_ignore_npcs;
    j[xorstr("esp_ignore_dead")] = p.esp_ignore_dead;
    j[xorstr("show_local_player")] = p.show_local_player;
    j[xorstr("team_check_color")] = nlohmann::json::array({p.team_check_color[0], p.team_check_color[1], p.team_check_color[2], p.team_check_color[3]});
    j[xorstr("playerlist_display_peds")] = p.playerlist_display_peds;
    j[xorstr("tracer")] = p.tracer;
    j[xorstr("tracer_duration")] = p.tracer_duration;
    j[xorstr("tracer_color")] = nlohmann::json::array({p.tracer_color[0], p.tracer_color[1], p.tracer_color[2], p.tracer_color[3]});
    j[xorstr("tracer_thickness")] = p.tracer_thickness;
    j[xorstr("player_chams")] = p.player_chams;
    j[xorstr("player_chams_flicker")] = p.player_chams_flicker;
    j[xorstr("player_chams_color")] = nlohmann::json::array({p.player_chams_color[0], p.player_chams_color[1], p.player_chams_color[2], p.player_chams_color[3]});
    j[xorstr("tint_players")] = p.tint_players;
    j[xorstr("tint_players_color")] = nlohmann::json::array({p.tint_players_color[0], p.tint_players_color[1], p.tint_players_color[2], p.tint_players_color[3]});
    j[xorstr("override_sky_color")] = p.override_sky_color;
    j[xorstr("sky_color")] = nlohmann::json::array({p.sky_color[0], p.sky_color[1], p.sky_color[2], p.sky_color[3]});
    j[xorstr("enable_sky_zenith_color")] = p.enable_sky_zenith_color;
    j[xorstr("sky_zenith_color")] = nlohmann::json::array({p.sky_zenith_color[0], p.sky_zenith_color[1], p.sky_zenith_color[2], p.sky_zenith_color[3]});
    j[xorstr("enable_sky_sun_color")] = p.enable_sky_sun_color;
    j[xorstr("sky_sun_color")] = nlohmann::json::array({p.sky_sun_color[0], p.sky_sun_color[1], p.sky_sun_color[2], p.sky_sun_color[3]});
    j[xorstr("enable_sky_sun_disc")] = p.enable_sky_sun_disc;
    j[xorstr("sky_sun_disc_color")] = nlohmann::json::array({p.sky_sun_disc_color[0], p.sky_sun_disc_color[1], p.sky_sun_disc_color[2], p.sky_sun_disc_color[3]});
    j[xorstr("sky_sun_disc_size")] = p.sky_sun_disc_size;
    j[xorstr("enable_sky_moon")] = p.enable_sky_moon;
    j[xorstr("sky_moon_color")] = nlohmann::json::array({p.sky_moon_color[0], p.sky_moon_color[1], p.sky_moon_color[2], p.sky_moon_color[3]});
    j[xorstr("sky_moon_disc_size")] = p.sky_moon_disc_size;
    j[xorstr("sky_moon_iten")] = p.sky_moon_iten;
    j[xorstr("enable_sky_stars")] = p.enable_sky_stars;
    j[xorstr("sky_stars_iten")] = p.sky_stars_iten;
    j[xorstr("enable_sky_clouds")] = p.enable_sky_clouds;
    j[xorstr("sky_cloud_density_mult")] = p.sky_cloud_density_mult;
    j[xorstr("sky_cloud_mid_col")] = nlohmann::json::array({p.sky_cloud_mid_col[0], p.sky_cloud_mid_col[1], p.sky_cloud_mid_col[2], p.sky_cloud_mid_col[3]});
    j[xorstr("sky_cloud_base_col")] = nlohmann::json::array({p.sky_cloud_base_col[0], p.sky_cloud_base_col[1], p.sky_cloud_base_col[2], p.sky_cloud_base_col[3]});
    j[xorstr("sky_cloud_overall_strength")] = p.sky_cloud_overall_strength;
    j[xorstr("enable_light_rays")] = p.enable_light_rays;
    j[xorstr("light_ray_mult")] = p.light_ray_mult;
    j[xorstr("light_ray_col")] = nlohmann::json::array({p.light_ray_col[0], p.light_ray_col[1], p.light_ray_col[2], p.light_ray_col[3]});
    j[xorstr("enable_fog_haze")] = p.enable_fog_haze;
    j[xorstr("fog_haze_col")] = nlohmann::json::array({p.fog_haze_col[0], p.fog_haze_col[1], p.fog_haze_col[2], p.fog_haze_col[3]});
    j[xorstr("fog_haze_density")] = p.fog_haze_density;
    j[xorstr("visible_check")] = p.visible_check;
    j[xorstr("visible_check_color")] = nlohmann::json::array({p.visible_check_color[0], p.visible_check_color[1], p.visible_check_color[2], p.visible_check_color[3]});
    j[xorstr("admin_check_esp")] = p.admin_check_esp;
    j[xorstr("admin_check_esp_color")] = nlohmann::json::array({p.admin_check_esp_color[0], p.admin_check_esp_color[1], p.admin_check_esp_color[2], p.admin_check_esp_color[3]});
    j[xorstr("filled_box")] = p.filled_box;
    j[xorstr("filled_box_color")] = nlohmann::json::array({p.filled_box_color[0], p.filled_box_color[1], p.filled_box_color[2], p.filled_box_color[3]});
    j[xorstr("skeleton_color")] = nlohmann::json::array({p.skeleton_color[0], p.skeleton_color[1], p.skeleton_color[2], p.skeleton_color[3]});
    j[xorstr("names_color")] = nlohmann::json::array({p.names_color[0], p.names_color[1], p.names_color[2], p.names_color[3]});
    j[xorstr("names_pos")] = p.names_pos;
    j[xorstr("weapon_name")] = p.weapon_name;
    j[xorstr("weapon_name_color")] = nlohmann::json::array({p.weapon_name_color[0], p.weapon_name_color[1], p.weapon_name_color[2], p.weapon_name_color[3]});
    j[xorstr("weapon_name_pos")] = p.weapon_name_pos;
    j[xorstr("distance_color")] = nlohmann::json::array({p.distance_color[0], p.distance_color[1], p.distance_color[2], p.distance_color[3]});
    j[xorstr("dotbones_color")] = nlohmann::json::array({p.dotbones_color[0], p.dotbones_color[1], p.dotbones_color[2], p.dotbones_color[3]});
    j[xorstr("distance_pos")] = p.distance_pos;
    j[xorstr("armor_bar")] = p.armor_bar;
    j[xorstr("armor_bar_pos")] = p.armor_bar_pos;
    j[xorstr("health_bar_pos")] = p.health_bar_pos;

    j[xorstr("outline_text")] = p.outline_text;
    j[xorstr("opacity")] = p.opacity;
    j[xorstr("line_thickness")] = p.line_thickness;
    j[xorstr("font_size")] = p.font_size;
    j[xorstr("icon_size")] = p.icon_size;
    j[xorstr("enable_chams")] = p.enable_chams;
    j[xorstr("chams_visible_color")] = nlohmann::json::array({p.chams_visible_color[0], p.chams_visible_color[1], p.chams_visible_color[2], p.chams_visible_color[3]});
    j[xorstr("chams_invisible_color")] = nlohmann::json::array({p.chams_invisible_color[0], p.chams_invisible_color[1], p.chams_invisible_color[2], p.chams_invisible_color[3]});
    j[xorstr("wireframe")] = p.wireframe;
    j[xorstr("flat_shading")] = p.flat_shading;
    j[xorstr("visualize_aimbot")] = p.visualize_aimbot;
    j[xorstr("visualize_aimbot_color")] = nlohmann::json::array({p.visualize_aimbot_color[0], p.visualize_aimbot_color[1], p.visualize_aimbot_color[2], p.visualize_aimbot_color[3]});
    j[xorstr("player_behind_wall")] = p.player_behind_wall;
    j[xorstr("player_behind_wall_color")] = nlohmann::json::array({p.player_behind_wall_color[0], p.player_behind_wall_color[1], p.player_behind_wall_color[2], p.player_behind_wall_color[3]});
    j[xorstr("behind_selection")] = p.behind_selection;
    j[xorstr("teammate")] = p.teammate;
    j[xorstr("teammate_behind_wall")] = p.teammate_behind_wall;
    j[xorstr("teammate_behind_wall_color")] = nlohmann::json::array({p.teammate_behind_wall_color[0], p.teammate_behind_wall_color[1], p.teammate_behind_wall_color[2], p.teammate_behind_wall_color[3]});

    j[xorstr("vehicle_esp")] = p.vehicle_esp;
    j[xorstr("vehicle_max_distance")] = p.vehicle_max_distance;
    j[xorstr("vehicle_snaplines")] = p.vehicle_snaplines;
    j[xorstr("vehicle_snaplines_color")] = nlohmann::json::array({p.vehicle_snaplines_color[0], p.vehicle_snaplines_color[1], p.vehicle_snaplines_color[2], p.vehicle_snaplines_color[3]});
    j[xorstr("vehicle_name")] = p.vehicle_name;
    j[xorstr("vehicle_distance")] = p.vehicle_distance;
    j[xorstr("object_esp")] = p.object_esp;
    j[xorstr("object_name")] = p.object_name;
    j[xorstr("object_distance")] = p.object_distance;
    j[xorstr("object_max_distance")] = p.object_max_distance;
    j[xorstr("object_name_color")] = nlohmann::json::array({p.object_name_color[0], p.object_name_color[1], p.object_name_color[2], p.object_name_color[3]});
    j[xorstr("vehicle_lock")] = p.vehicle_lock;
    j[xorstr("vehicle_god_mode")] = p.vehicle_god_mode;
    j[xorstr("no_clip")] = p.no_clip;
    j[xorstr("spinbot")] = p.spinbot;
    j[xorstr("strafe")] = p.strafe;
    j[xorstr("strafe_speed")] = p.strafe_speed;
    j[xorstr("teleport_behind_enemy")] = p.teleport_behind_enemy;
    j[xorstr("god_mode")] = p.god_mode;
    j[xorstr("anti_afk")] = p.anti_afk;
    j[xorstr("anti_afk_speed")] = p.anti_afk_speed;
    j[xorstr("fake_lag")] = p.fake_lag;
    j[xorstr("fake_lag_speed")] = p.fake_lag_speed;
    j[xorstr("always_lag")] = p.always_lag;
    j[xorstr("anti_aim_block")] = p.anti_aim_block;
    j[xorstr("teleport")] = p.teleport;
    j[xorstr("physgun")] = p.physgun;
    j[xorstr("physgun_fov")] = p.physgun_fov;
    j[xorstr("physgun_range")] = p.physgun_range;
    j[xorstr("bring_vehicle")] = p.bring_vehicle;
    j[xorstr("warp_into_vehicle")] = p.warp_into_vehicle;
    j[xorstr("super_jump")] = p.super_jump;
    j[xorstr("fast_run")] = p.fast_run;
    j[xorstr("run_speed")] = p.run_speed;
    j[xorstr("horn_boost_enabled")] = p.horn_boost_enabled;
    j[xorstr("horn_boost_speed")] = p.horn_boost_speed;
    j[xorstr("modify_vehicle_acceleration")] = p.modify_vehicle_acceleration;
    j[xorstr("vehicle_acceleration_value")] = p.vehicle_acceleration_value;
    j[xorstr("modify_vehicle_traction")] = p.modify_vehicle_traction;
    j[xorstr("vehicle_traction_value")] = p.vehicle_traction_value;
    j[xorstr("teleport_behind_enemy_distance")] = p.teleport_behind_enemy_distance;
    j[xorstr("teleport_behind_enemy_fov")] = p.teleport_behind_enemy_fov;
    j[xorstr("teleport_behind_enemy_range")] = p.teleport_behind_enemy_range;
    j[xorstr("noclip_speed")] = p.noclip_speed;
    j[xorstr("max_health")] = p.max_health;
    j[xorstr("max_armor")] = p.max_armor;
    j[xorstr("infinite_stamina")] = p.infinite_stamina;
    j[xorstr("seat_belt")] = p.seat_belt;
    j[xorstr("anti_headshot")] = p.anti_headshot;
    j[xorstr("beast_jump")] = p.beast_jump;
    j[xorstr("super_jump")] = p.super_jump;
    j[xorstr("explosive_fist")] = p.explosive_fist;
    j[xorstr("fire_ammo")] = p.fire_ammo;
    j[xorstr("explosive_ammo")] = p.explosive_ammo;
    j[xorstr("no_rag_doll")] = p.no_rag_doll;
    j[xorstr("invisible")] = p.invisible;
    j[xorstr("inf_combat_roll")] = p.inf_combat_roll;
    j[xorstr("force_weapon_wheel")] = p.force_weapon_wheel;
    j[xorstr("steal_car")] = p.steal_car;
    j[xorstr("shrink_enabled")] = p.shrink_enabled;
    j[xorstr("shrink_scale")] = p.shrink_scale;
    j[xorstr("big_ped_enabled")] = p.big_ped_enabled;
    j[xorstr("big_ped_scale")] = p.big_ped_scale;
    j[xorstr("custom_fov")] = p.custom_fov;
    j[xorstr("fov_value")] = p.fov_value;
    j[xorstr("damage_boost")] = p.damage_boost;
    j[xorstr("damage_boost_value")] = p.damage_boost_value;
    j[xorstr("recoil_value")] = p.recoil_value;
    j[xorstr("spread_value")] = p.spread_value;
    j[xorstr("no_reload")] = p.no_reload;
    j[xorstr("weapon_range")] = p.weapon_range;
    j[xorstr("weapon_size_enabled")] = p.weapon_size_enabled;
    j[xorstr("weapon_size_value")] = p.weapon_size_value;
    j[xorstr("explode_vehicle")] = p.explode_vehicle;
    j[xorstr("change_plate")] = p.change_plate;
	j[xorstr("plate")] = std::string(p.plate);
	j[xorstr("vehicle_spawn_name")] = std::string(p.vehicle_spawn_name);
	j[xorstr("vehicle_spawn_networked")] = p.vehicle_spawn_networked;
	j[xorstr("ped_spawn_name")] = std::string(p.ped_spawn_name);
	j[xorstr("ped_spawn_networked")] = p.ped_spawn_networked;
	j[xorstr("prop_spawn_name")] = std::string(p.prop_spawn_name);
	j[xorstr("prop_spawn_networked")] = p.prop_spawn_networked;
	j[xorstr("repair_vehicle")] = p.repair_vehicle;
    j[xorstr("apply_color_change")] = p.apply_color_change;
    j[xorstr("primary_vehicle_color")] = nlohmann::json::array({p.primary_vehicle_color[0], p.primary_vehicle_color[1], p.primary_vehicle_color[2], p.primary_vehicle_color[3]});
    j[xorstr("secondary_vehicle_color")] = nlohmann::json::array({p.secondary_vehicle_color[0], p.secondary_vehicle_color[1], p.secondary_vehicle_color[2], p.secondary_vehicle_color[3]});
    j[xorstr("modify_gravity")] = p.modify_gravity;
    j[xorstr("gravity_value")] = p.gravity_value;
    j[xorstr("rocket_boost")] = p.rocket_boost;
    j[xorstr("infinite_ammo")] = p.infinite_ammo;
    j[xorstr("no_recoil_exploit")] = p.no_recoil_exploit;
    j[xorstr("no_spread")] = p.no_spread;
    j[xorstr("tp_to_bullet")] = p.tp_to_bullet;
    j[xorstr("freeze_ammo")] = p.freeze_ammo;
    j[xorstr("rapid_fire")] = p.rapid_fire;
    j[xorstr("invisible_spoof")] = p.invisible_spoof;
    j[xorstr("disable_melee")] = p.disable_melee;
    j[xorstr("no_ragdoll_bullet")] = p.no_ragdoll_bullet;
    j[xorstr("no_ragdoll_explosion")] = p.no_ragdoll_explosion;
    j[xorstr("no_ragdoll_fire")] = p.no_ragdoll_fire;
    j[xorstr("no_ragdoll_vehicle")] = p.no_ragdoll_vehicle;
    j[xorstr("treat_as_player_targeting")] = p.treat_as_player_targeting;
    j[xorstr("block_weapon_switch")] = p.block_weapon_switch;

    j[xorstr("disable_evasive_dives")] = p.disable_evasive_dives;
    j[xorstr("disable_player_lockon")] = p.disable_player_lockon;
    j[xorstr("disable_unarmed_drivebys")] = p.disable_unarmed_drivebys;
    j[xorstr("no_collision")] = p.no_collision;
    j[xorstr("remove_flashbang_effect")] = p.remove_flashbang_effect;
    j[xorstr("remove_smoke_grenades")] = p.remove_smoke_grenades;
    j[xorstr("remove_skybox")] = p.remove_skybox;
    j[xorstr("the_power_of_flashbang_one")] = p.the_power_of_flashbang_one;
    j[xorstr("the_power_of_flashbang_two")] = p.the_power_of_flashbang_two;
    j[xorstr("transparent_walls_one")] = p.transparent_walls_one;
    j[xorstr("transparent_walls_two")] = p.transparent_walls_two;
    j[xorstr("fps_counter")] = p.fps_counter;
    j[xorstr("coordinates")] = p.coordinates;
    j[xorstr("enhanced_minimap")] = p.enhanced_minimap;
    j[xorstr("array_list")] = p.array_list;
    j[xorstr("array_list_col")] = p.array_list_col;
    j[xorstr("display_monitor_index")] = p.display_monitor_index;
    j[xorstr("enable_rgb_particles")] = p.enable_rgb_particles;
    j[xorstr("process_priority")] = p.process_priority;

    j[xorstr("custom_crosshair")] = p.custom_crosshair;
    j[xorstr("watermark")] = p.watermark;
    j[xorstr("stream_proof")] = p.stream_proof;
    j[xorstr("vsync")] = p.vsync;
    j[xorstr("second_monitor_display")] = p.second_monitor_display;
    j[xorstr("menu_keybind")] = p.menu_keybind;
    j[xorstr("unload_keybind")] = p.unload_keybind;
    j[xorstr("web_only")] = p.web_only;
    j[xorstr("crosshair_style")] = p.crosshair_style;
    j[xorstr("crosshair_size")] = p.crosshair_size;
    j[xorstr("crosshair_thickness")] = p.crosshair_thickness;
    j[xorstr("crosshair_color")] = nlohmann::json::array({p.crosshair_color[0], p.crosshair_color[1], p.crosshair_color[2], p.crosshair_color[3]});
    j[xorstr("friends_marker")] = p.friends_marker;
    j[xorstr("radar")] = p.radar;
    {
        nlohmann::json arr = nlohmann::json::array();
        for (int i = 0; i < 20; i++) arr.push_back(p.dotbones_select[i]);
        j[xorstr("dotbones_select")] = std::move(arr);
    }
    j[xorstr("fake_fps_enabled")] = p.fake_fps_enabled;
    j[xorstr("fake_fps_range_mode")] = p.fake_fps_range_mode;
    j[xorstr("fake_fps_target")] = p.fake_fps_target;
    j[xorstr("fake_fps_min")] = p.fake_fps_min;
    j[xorstr("fake_fps_max")] = p.fake_fps_max;
    return j;
}

inline void ApplyOptionsParamFromJson(const nlohmann::json& j, options_t* p) {
    if (!p) return;
    auto arr4 = [&j](const char* key, float* out) {
        if (j.contains(key) && j[key].is_array() && j[key].size() >= 4)
            for (int i = 0; i < 4; i++) out[i] = j[key][i];
    };
    auto arr20 = [&j](const char* key, bool* out) {
        if (j.contains(key) && j[key].is_array())
            for (size_t i = 0; i < 20 && i < j[key].size(); i++) out[i] = j[key][i];
    };
#define OPT_BOOL(k) if (j.contains(xorstr(#k))) p->k = j[xorstr(#k)]
#define OPT_INT(k) if (j.contains(xorstr(#k))) p->k = j[xorstr(#k)]
#define OPT_FLOAT(k) if (j.contains(xorstr(#k))) p->k = j[xorstr(#k)]
#define OPT_STR(k, len) if (j.contains(xorstr(#k))) { std::string tmp = j[xorstr(#k)]; strncpy_s(p->k, sizeof(p->k), tmp.c_str(), _TRUNCATE); }
    OPT_BOOL(enable_aimbot); OPT_BOOL(fiveguard_bypass); OPT_BOOL(fov_circle); OPT_FLOAT(fov_size);
    arr4(xorstr("fov_color"), p->fov_color);
    OPT_FLOAT(smoothing); OPT_INT(hitbone); OPT_INT(aim_distance); OPT_BOOL(ignore_npcs); OPT_BOOL(ignore_players);
    OPT_BOOL(check_visible); OPT_BOOL(target_combat_roll); OPT_BOOL(target_jump); OPT_BOOL(target_line);
    OPT_FLOAT(smooth_horizontal); OPT_FLOAT(smooth_vertical); OPT_INT(aimbot_speed); OPT_BOOL(aim_curving);
    OPT_FLOAT(curve_strength); OPT_BOOL(in_vehicle_aimbot); OPT_BOOL(use_prediction); OPT_FLOAT(prediction_time); OPT_FLOAT(randomize_angle);
    OPT_BOOL(silent_aim); OPT_BOOL(magic_bullets); OPT_BOOL(silent_fov_circle); OPT_FLOAT(silent_fov_size);
    OPT_BOOL(silent_smart_fov); OPT_BOOL(silent_dual_fov); OPT_FLOAT(silent_fov_near); OPT_FLOAT(silent_fov_far); OPT_INT(silent_dual_fov_distance);
    arr4(xorstr("silent_fov_color"), p->silent_fov_color);
    OPT_INT(silent_hitbone); OPT_INT(silent_hit_chance); OPT_FLOAT(silent_jitter); OPT_BOOL(silent_ignore_npcs); OPT_BOOL(silent_ignore_players);
    OPT_BOOL(silent_check_visible); OPT_BOOL(silent_target_combat_roll); OPT_BOOL(silent_target_jump); OPT_BOOL(silent_target_line); OPT_BOOL(smart_trigger); OPT_INT(miss_chance);
    OPT_INT(silent_max_distance); OPT_INT(silent_reaction_time); OPT_BOOL(silent_random_hitbone); OPT_BOOL(silent_aim_curving); OPT_FLOAT(silent_curve_strength); OPT_INT(magic_max_distance);
    OPT_BOOL(enable_triggerbot); OPT_INT(triggerbot_delay); OPT_INT(triggerbot_hit_chance); OPT_INT(triggerbot_hitbone); OPT_BOOL(triggerbot_target_line);
    OPT_INT(triggerbot_delay_jitter); OPT_INT(triggerbot_shot_duration); OPT_INT(triggerbot_cooldown); OPT_INT(triggerbot_max_distance);
    OPT_BOOL(triggerbot_curving); OPT_FLOAT(triggerbot_curve_strength);
    OPT_BOOL(triggerbot_ignore_npcs); OPT_BOOL(triggerbot_ignore_friends); OPT_BOOL(triggerbot_check_visible);
    OPT_BOOL(triggerbot_target_combat_roll); OPT_BOOL(triggerbot_target_jump); OPT_BOOL(triggerbot_fov_circle); OPT_FLOAT(triggerbot_fov_size);
    arr4(xorstr("triggerbot_fov_color"), p->triggerbot_fov_color);

    OPT_BOOL(disable_aimbot_while_flashed); OPT_BOOL(disable_aimbot_through_smoke); OPT_FLOAT(assist_delay);
    OPT_BOOL(enable_recoil); OPT_BOOL(return_crosshair); OPT_INT(enable_bullet); OPT_INT(x_axis); OPT_INT(y_axis);
    OPT_INT(hitting_chance_one); OPT_INT(hitting_chance_two); OPT_BOOL(disable_triggerbot_through_smoke);
    OPT_BOOL(disable_triggerbot_while_flashed); OPT_BOOL(enable_antiaimbot); OPT_INT(add_lby_flip_yaw); OPT_INT(real_yaw);

    OPT_BOOL(enable_esp); OPT_BOOL(dormant); OPT_BOOL(bounding_box); OPT_INT(box_style); arr4(xorstr("box_color"), p->box_color);
    OPT_BOOL(skeleton); OPT_BOOL(names); OPT_BOOL(distance); OPT_BOOL(dotbones); arr20(xorstr("dotbones_select"), p->dotbones_select);
    OPT_BOOL(arrows); arr4(xorstr("arrows_color"), p->arrows_color); OPT_FLOAT(arrows_size);
    OPT_BOOL(health_bar); OPT_BOOL(snaplines); arr4(xorstr("snaplines_color"), p->snaplines_color);
    OPT_FLOAT(esp_max_distance); OPT_BOOL(team_check); OPT_BOOL(esp_ignore_npcs); OPT_BOOL(esp_ignore_dead);
    OPT_BOOL(show_local_player); arr4(xorstr("team_check_color"), p->team_check_color); OPT_BOOL(playerlist_display_peds);
    OPT_BOOL(tracer); OPT_FLOAT(tracer_duration); arr4(xorstr("tracer_color"), p->tracer_color); OPT_FLOAT(tracer_thickness);
    OPT_BOOL(player_chams); OPT_BOOL(player_chams_flicker); arr4(xorstr("player_chams_color"), p->player_chams_color);
    OPT_BOOL(tint_players); arr4(xorstr("tint_players_color"), p->tint_players_color);
    OPT_BOOL(override_sky_color); arr4(xorstr("sky_color"), p->sky_color);
    OPT_BOOL(enable_sky_zenith_color); arr4(xorstr("sky_zenith_color"), p->sky_zenith_color);
    OPT_BOOL(enable_sky_sun_color); arr4(xorstr("sky_sun_color"), p->sky_sun_color);
    OPT_BOOL(enable_sky_sun_disc); arr4(xorstr("sky_sun_disc_color"), p->sky_sun_disc_color); OPT_FLOAT(sky_sun_disc_size);
    OPT_BOOL(enable_sky_moon); arr4(xorstr("sky_moon_color"), p->sky_moon_color); OPT_FLOAT(sky_moon_disc_size);
    OPT_FLOAT(sky_moon_iten); OPT_BOOL(enable_sky_stars); OPT_FLOAT(sky_stars_iten); OPT_BOOL(enable_sky_clouds); OPT_FLOAT(sky_cloud_density_mult);
    arr4(xorstr("sky_cloud_mid_col"), p->sky_cloud_mid_col); arr4(xorstr("sky_cloud_base_col"), p->sky_cloud_base_col);
    OPT_FLOAT(sky_cloud_overall_strength); OPT_BOOL(enable_light_rays); OPT_FLOAT(light_ray_mult); arr4(xorstr("light_ray_col"), p->light_ray_col);
    OPT_BOOL(enable_fog_haze); arr4(xorstr("fog_haze_col"), p->fog_haze_col); OPT_FLOAT(fog_haze_density);
    OPT_BOOL(visible_check); arr4(xorstr("visible_check_color"), p->visible_check_color);
    OPT_BOOL(admin_check_esp); arr4(xorstr("admin_check_esp_color"), p->admin_check_esp_color);
    OPT_BOOL(filled_box); arr4(xorstr("filled_box_color"), p->filled_box_color); arr4(xorstr("skeleton_color"), p->skeleton_color);
    arr4(xorstr("names_color"), p->names_color); OPT_INT(names_pos); OPT_BOOL(weapon_name); arr4(xorstr("weapon_name_color"), p->weapon_name_color);
    OPT_INT(weapon_name_pos); arr4(xorstr("distance_color"), p->distance_color); arr4(xorstr("dotbones_color"), p->dotbones_color);
    OPT_INT(distance_pos); OPT_BOOL(armor_bar); OPT_INT(armor_bar_pos); OPT_INT(health_bar_pos);

    OPT_BOOL(outline_text); OPT_FLOAT(opacity); OPT_FLOAT(line_thickness); OPT_FLOAT(font_size); OPT_FLOAT(icon_size);
    OPT_BOOL(enable_chams); arr4(xorstr("chams_visible_color"), p->chams_visible_color); arr4(xorstr("chams_invisible_color"), p->chams_invisible_color);
    OPT_BOOL(wireframe); OPT_BOOL(flat_shading); OPT_BOOL(visualize_aimbot); arr4(xorstr("visualize_aimbot_color"), p->visualize_aimbot_color);
    OPT_BOOL(player_behind_wall); arr4(xorstr("player_behind_wall_color"), p->player_behind_wall_color); OPT_INT(behind_selection);
    OPT_BOOL(teammate); OPT_BOOL(teammate_behind_wall); arr4(xorstr("teammate_behind_wall_color"), p->teammate_behind_wall_color);

    OPT_BOOL(vehicle_esp); OPT_FLOAT(vehicle_max_distance); OPT_BOOL(vehicle_snaplines); arr4(xorstr("vehicle_snaplines_color"), p->vehicle_snaplines_color);
    OPT_BOOL(vehicle_name); OPT_BOOL(vehicle_distance);
    OPT_BOOL(object_esp); OPT_BOOL(object_name); OPT_BOOL(object_distance); OPT_FLOAT(object_max_distance); arr4(xorstr("object_name_color"), p->object_name_color);
    OPT_BOOL(vehicle_lock); OPT_BOOL(vehicle_god_mode);
    OPT_BOOL(no_clip); OPT_BOOL(spinbot); OPT_BOOL(strafe); OPT_INT(strafe_speed); OPT_BOOL(teleport_behind_enemy); OPT_BOOL(god_mode); OPT_BOOL(anti_afk); OPT_INT(anti_afk_speed); OPT_BOOL(fake_lag); OPT_INT(fake_lag_speed); OPT_BOOL(always_lag); OPT_BOOL(anti_aim_block);
    OPT_BOOL(teleport);
    OPT_BOOL(physgun); OPT_FLOAT(physgun_fov); OPT_INT(physgun_range);
    OPT_BOOL(bring_vehicle);
    OPT_BOOL(warp_into_vehicle);
    OPT_BOOL(super_jump);
    OPT_BOOL(fast_run);
    OPT_FLOAT(run_speed);
    OPT_BOOL(horn_boost_enabled);
    OPT_FLOAT(horn_boost_speed);
    OPT_BOOL(modify_vehicle_acceleration);
    OPT_FLOAT(vehicle_acceleration_value);
    OPT_BOOL(modify_vehicle_traction);
    OPT_FLOAT(vehicle_traction_value); OPT_FLOAT(teleport_behind_enemy_distance); OPT_FLOAT(teleport_behind_enemy_fov); OPT_INT(teleport_behind_enemy_range);
    OPT_FLOAT(noclip_speed); OPT_FLOAT(max_health); OPT_FLOAT(max_armor); OPT_BOOL(infinite_stamina); OPT_BOOL(seat_belt); OPT_BOOL(anti_headshot);
    OPT_BOOL(beast_jump); OPT_BOOL(super_jump); OPT_BOOL(explosive_fist); OPT_BOOL(fire_ammo); OPT_BOOL(explosive_ammo); OPT_BOOL(no_rag_doll); OPT_BOOL(invisible);
    OPT_BOOL(inf_combat_roll); OPT_BOOL(force_weapon_wheel); OPT_BOOL(steal_car); OPT_BOOL(shrink_enabled); OPT_FLOAT(shrink_scale); OPT_BOOL(big_ped_enabled); OPT_FLOAT(big_ped_scale);
    OPT_BOOL(custom_fov); OPT_FLOAT(fov_value); OPT_BOOL(damage_boost); OPT_FLOAT(damage_boost_value);
    OPT_FLOAT(recoil_value); OPT_FLOAT(spread_value); OPT_BOOL(no_reload); OPT_FLOAT(weapon_range);
    OPT_BOOL(weapon_size_enabled); OPT_FLOAT(weapon_size_value);
    OPT_BOOL(infinite_ammo); OPT_BOOL(no_recoil_exploit); OPT_BOOL(no_spread);
    OPT_BOOL(tp_to_bullet); OPT_BOOL(freeze_ammo);
    OPT_BOOL(rapid_fire); OPT_BOOL(invisible_spoof);
    OPT_BOOL(disable_melee); OPT_BOOL(no_ragdoll_bullet); OPT_BOOL(no_ragdoll_explosion); OPT_BOOL(no_ragdoll_fire); OPT_BOOL(no_ragdoll_vehicle);
    OPT_BOOL(treat_as_player_targeting); OPT_BOOL(block_weapon_switch);

    OPT_BOOL(disable_evasive_dives); OPT_BOOL(disable_player_lockon); OPT_BOOL(disable_unarmed_drivebys); OPT_BOOL(no_collision);
    OPT_BOOL(remove_flashbang_effect); OPT_BOOL(remove_smoke_grenades); OPT_BOOL(remove_skybox);
    OPT_INT(the_power_of_flashbang_one); OPT_INT(the_power_of_flashbang_two);
    OPT_FLOAT(transparent_walls_one); OPT_FLOAT(transparent_walls_two);
    OPT_BOOL(fps_counter); OPT_BOOL(coordinates); OPT_BOOL(enhanced_minimap); OPT_BOOL(array_list); OPT_BOOL(array_list_col);
    OPT_INT(display_monitor_index); OPT_BOOL(enable_rgb_particles); OPT_INT(process_priority);

    OPT_BOOL(custom_crosshair); OPT_BOOL(watermark); OPT_BOOL(stream_proof); OPT_BOOL(vsync); OPT_BOOL(second_monitor_display);
    OPT_INT(menu_keybind); OPT_INT(unload_keybind); OPT_BOOL(web_only);
    OPT_INT(crosshair_style); OPT_FLOAT(crosshair_size); OPT_FLOAT(crosshair_thickness); arr4(xorstr("crosshair_color"), p->crosshair_color);
    OPT_BOOL(friends_marker); OPT_BOOL(radar);
    OPT_BOOL(fake_fps_enabled); OPT_BOOL(fake_fps_range_mode);
    OPT_INT(fake_fps_target); OPT_INT(fake_fps_min); OPT_INT(fake_fps_max);
    OPT_BOOL(explode_vehicle); OPT_BOOL(change_plate);
    if (j.contains(xorstr("plate"))) { std::string tmp = j[xorstr("plate")]; strncpy_s(p->plate, sizeof(p->plate), tmp.c_str(), _TRUNCATE); }
    if (j.contains(xorstr("vehicle_spawn_name"))) { std::string tmp = j[xorstr("vehicle_spawn_name")]; strncpy_s(p->vehicle_spawn_name, sizeof(p->vehicle_spawn_name), tmp.c_str(), _TRUNCATE); }
    OPT_BOOL(vehicle_spawn_networked);
    if (j.contains(xorstr("ped_spawn_name"))) { std::string tmp = j[xorstr("ped_spawn_name")]; strncpy_s(p->ped_spawn_name, sizeof(p->ped_spawn_name), tmp.c_str(), _TRUNCATE); }
    OPT_BOOL(ped_spawn_networked);
    if (j.contains(xorstr("prop_spawn_name"))) { std::string tmp = j[xorstr("prop_spawn_name")]; strncpy_s(p->prop_spawn_name, sizeof(p->prop_spawn_name), tmp.c_str(), _TRUNCATE); }
    OPT_BOOL(prop_spawn_networked);
    OPT_BOOL(repair_vehicle);
#undef OPT_BOOL
#undef OPT_INT
#undef OPT_FLOAT
#undef OPT_STR
}

}
